export const lists = [
  {
    id: Date.now(),
    logo: "logo1.avif",
    name: "Business",
    photo: "photo1.webp",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 300,
    notlike: 1,
    comment: 0,
    trending: true,
    time: "17h",
  },
  {
    id: Date.now(),
    logo: "logo2.png",
    name: "CNBC",
    photo: "photo2.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 77,
    notlike: 0,
    comment: 1,
    trending: false,
    time: "1d",
  },
  {
    id: Date.now(),
    logo: "logo3.jpg",
    name: "Aura",
    photo: "photo3.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 120,
    notlike: 0,
    comment: 80,
    trending: false,
    time: "23h",
  },
  {
    id: Date.now(),
    logo: "logo4.webp",
    name: "C-Cat",
    photo: "photo4.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 300,
    notlike: 0,
    comment: 10,
    trending: false,
    time: "1h",
  },
  {
    id: Date.now(),
    logo: "logo5.webp",
    name: "braham",
    photo: "photo5.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 30,
    notlike: 0,
    comment: 10,
    trending: false,
    time: "4d",
  },
  {
    id: Date.now(),
    logo: "logo6.jpg",
    name: "King",
    photo: "photo6.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 100,
    notlike: 0,
    comment: 30,
    trending: true,
    time: "5h",
  },
  {
    id: Date.now(),
    logo: "logo6.jpg",
    name: "Super-man",
    photo: "photo9.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 120,
    notlike: 1,
    comment: 0,
    trending: true,
    time: "5h",
  },
  {
    id: Date.now(),
    logo: "logo11.jpg",
    name: "Technology",
    photo: "photo16.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 999,
    notlike: 0,
    comment: 100,
    trending: true,
    time: "9h",
  },
  {
    id: Date.now(),
    logo: "logo11.jpg",
    name: "Technology",
    photo: "photo14.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 441,
    notlike: 0,
    comment: 34,
    trending: true,
    time: "1d",
  },
  {
    id: Date.now(),
    logo: "logo10.jpg",
    name: "Trainning",
    photo: "photo15.jpg",
    description:
      "Procedure statement of submitting a statement to such conditions",
    like: 220,
    notlike: 0,
    comment: 14,
    trending: false,
    time: "2d",
  },
];
